# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_fuction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mapfuction(object):
    def setupUi(self, Mapfuction):
        Mapfuction.setObjectName("Mapfuction")
        Mapfuction.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Mapfuction)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(Mapfuction)
        QtCore.QMetaObject.connectSlotsByName(Mapfuction)

    def retranslateUi(self, Mapfuction):
        _translate = QtCore.QCoreApplication.translate
        Mapfuction.setWindowTitle(_translate("Mapfuction", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mapfuction = QtWidgets.QWidget()
    ui = Ui_Mapfuction()
    ui.setupUi(Mapfuction)
    Mapfuction.show()
    sys.exit(app.exec_())
