# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddwidgetFunction(object):
    def setupUi(self, AddwidgetFunction):
        AddwidgetFunction.setObjectName("AddwidgetFunction")
        AddwidgetFunction.resize(586, 271)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddwidgetFunction)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(AddwidgetFunction)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setStyleSheet("QWidget#widget{border-color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-width:1px;}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(200, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(200, 100))
        self.label.setMaximumSize(QtCore.QSize(200, 100))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(AddwidgetFunction)
        self.pushButton.clicked.connect(self.pushButton.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddwidgetFunction)

    def retranslateUi(self, AddwidgetFunction):
        _translate = QtCore.QCoreApplication.translate
        AddwidgetFunction.setWindowTitle(_translate("AddwidgetFunction", "Form"))
        self.label.setText(_translate("AddwidgetFunction", "사진이 들어갈 공간"))
        self.pushButton.setText(_translate("AddwidgetFunction", "del"))
        self.label_5.setText(_translate("AddwidgetFunction", "간략 주소"))
        self.label_6.setText(_translate("AddwidgetFunction", "전화 번호"))
        self.label_4.setText(_translate("AddwidgetFunction", "상세 주소"))
        self.label_3.setText(_translate("AddwidgetFunction", "설명"))
        self.label_2.setText(_translate("AddwidgetFunction", "제목"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddwidgetFunction = QtWidgets.QWidget()
    ui = Ui_AddwidgetFunction()
    ui.setupUi(AddwidgetFunction)
    AddwidgetFunction.show()
    sys.exit(app.exec_())
