# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 799)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 550, 800))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 550, 800))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.background_lbl = QtWidgets.QLabel(self.login_page)
        self.background_lbl.setGeometry(QtCore.QRect(0, 0, 550, 800))
        self.background_lbl.setText("")
        self.background_lbl.setPixmap(QtGui.QPixmap("img/background.png"))
        self.background_lbl.setScaledContents(True)
        self.background_lbl.setObjectName("background_lbl")
        self.id_line = QtWidgets.QLineEdit(self.login_page)
        self.id_line.setGeometry(QtCore.QRect(170, 280, 210, 30))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.id_line.setFont(font)
        self.id_line.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.id_line.setObjectName("id_line")
        self.pw_line = QtWidgets.QLineEdit(self.login_page)
        self.pw_line.setGeometry(QtCore.QRect(170, 350, 210, 30))
        self.pw_line.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.pw_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_line.setObjectName("pw_line")
        self.error_lbl = QtWidgets.QLabel(self.login_page)
        self.error_lbl.setGeometry(QtCore.QRect(170, 380, 231, 21))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.error_lbl.setFont(font)
        self.error_lbl.setStyleSheet("color: rgb(239, 0, 0);\n"
"background-color: rgba(255, 255, 255, 00);")
        self.error_lbl.setText("")
        self.error_lbl.setObjectName("error_lbl")
        self.id_lbl = QtWidgets.QLabel(self.login_page)
        self.id_lbl.setGeometry(QtCore.QRect(170, 262, 56, 12))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.id_lbl.setFont(font)
        self.id_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.id_lbl.setObjectName("id_lbl")
        self.pw_lbl = QtWidgets.QLabel(self.login_page)
        self.pw_lbl.setGeometry(QtCore.QRect(170, 332, 56, 12))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.pw_lbl.setFont(font)
        self.pw_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pw_lbl.setObjectName("pw_lbl")
        self.login_btn = QtWidgets.QPushButton(self.login_page)
        self.login_btn.setGeometry(QtCore.QRect(170, 420, 65, 42))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"color: rgb(255, 255, 255);")
        self.login_btn.setObjectName("login_btn")
        self.join_btn = QtWidgets.QPushButton(self.login_page)
        self.join_btn.setGeometry(QtCore.QRect(240, 420, 65, 42))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.join_btn.setFont(font)
        self.join_btn.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.join_btn.setObjectName("join_btn")
        self.esc_btn = QtWidgets.QPushButton(self.login_page)
        self.esc_btn.setGeometry(QtCore.QRect(310, 420, 65, 42))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.esc_btn.setFont(font)
        self.esc_btn.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"color: rgb(255, 255, 255);")
        self.esc_btn.setObjectName("esc_btn")
        self.label_3 = QtWidgets.QLabel(self.login_page)
        self.label_3.setGeometry(QtCore.QRect(180, 170, 61, 71))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Bold")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.main_lbl = QtWidgets.QLabel(self.login_page)
        self.main_lbl.setGeometry(QtCore.QRect(165, 110, 221, 81))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Bold")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.main_lbl.setFont(font)
        self.main_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.main_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.main_lbl.setObjectName("main_lbl")
        self.stackedWidget.addWidget(self.login_page)
        self.join_page = QtWidgets.QWidget()
        self.join_page.setObjectName("join_page")
        self.background_lbl2 = QtWidgets.QLabel(self.join_page)
        self.background_lbl2.setGeometry(QtCore.QRect(0, 0, 550, 800))
        self.background_lbl2.setText("")
        self.background_lbl2.setPixmap(QtGui.QPixmap("img/background.png"))
        self.background_lbl2.setScaledContents(True)
        self.background_lbl2.setObjectName("background_lbl2")
        self.label = QtWidgets.QLabel(self.join_page)
        self.label.setGeometry(QtCore.QRect(165, 80, 221, 61))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Bold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.name_line = QtWidgets.QLineEdit(self.join_page)
        self.name_line.setGeometry(QtCore.QRect(175, 224, 200, 30))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.name_line.setFont(font)
        self.name_line.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.name_line.setObjectName("name_line")
        self.id_line2 = QtWidgets.QLineEdit(self.join_page)
        self.id_line2.setGeometry(QtCore.QRect(175, 288, 200, 30))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.id_line2.setFont(font)
        self.id_line2.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.id_line2.setObjectName("id_line2")
        self.pw_line2 = QtWidgets.QLineEdit(self.join_page)
        self.pw_line2.setGeometry(QtCore.QRect(175, 350, 200, 30))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.pw_line2.setFont(font)
        self.pw_line2.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.pw_line2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pw_line2.setObjectName("pw_line2")
        self.pwch_line = QtWidgets.QLineEdit(self.join_page)
        self.pwch_line.setGeometry(QtCore.QRect(175, 410, 200, 30))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.pwch_line.setFont(font)
        self.pwch_line.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.pwch_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwch_line.setObjectName("pwch_line")
        self.name_lbl = QtWidgets.QLabel(self.join_page)
        self.name_lbl.setGeometry(QtCore.QRect(175, 210, 56, 12))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.name_lbl.setFont(font)
        self.name_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.name_lbl.setObjectName("name_lbl")
        self.id_lbl2 = QtWidgets.QLabel(self.join_page)
        self.id_lbl2.setGeometry(QtCore.QRect(175, 272, 56, 12))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.id_lbl2.setFont(font)
        self.id_lbl2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.id_lbl2.setObjectName("id_lbl2")
        self.pw_lbl2 = QtWidgets.QLabel(self.join_page)
        self.pw_lbl2.setGeometry(QtCore.QRect(175, 333, 56, 12))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.pw_lbl2.setFont(font)
        self.pw_lbl2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pw_lbl2.setObjectName("pw_lbl2")
        self.pwch_lbl = QtWidgets.QLabel(self.join_page)
        self.pwch_lbl.setGeometry(QtCore.QRect(175, 392, 81, 16))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.pwch_lbl.setFont(font)
        self.pwch_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.pwch_lbl.setObjectName("pwch_lbl")
        self.age_com = QtWidgets.QComboBox(self.join_page)
        self.age_com.setGeometry(QtCore.QRect(175, 470, 200, 33))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.age_com.setFont(font)
        self.age_com.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:3px;")
        self.age_com.setObjectName("age_com")
        self.age_com.addItem("")
        self.age_com.addItem("")
        self.age_com.addItem("")
        self.age_com.addItem("")
        self.age_com.addItem("")
        self.age_com.addItem("")
        self.age_com.addItem("")
        self.age_lbl = QtWidgets.QLabel(self.join_page)
        self.age_lbl.setGeometry(QtCore.QRect(175, 452, 56, 12))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.age_lbl.setFont(font)
        self.age_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.age_lbl.setObjectName("age_lbl")
        self.cancel_btn = QtWidgets.QPushButton(self.join_page)
        self.cancel_btn.setGeometry(QtCore.QRect(188, 540, 81, 41))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"color: rgb(255, 255, 255);")
        self.cancel_btn.setObjectName("cancel_btn")
        self.clear_btn = QtWidgets.QPushButton(self.join_page)
        self.clear_btn.setGeometry(QtCore.QRect(275, 540, 81, 41))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"color: rgb(255, 255, 255);")
        self.clear_btn.setObjectName("clear_btn")
        self.error_lbl_2 = QtWidgets.QLabel(self.join_page)
        self.error_lbl_2.setGeometry(QtCore.QRect(175, 510, 231, 21))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.error_lbl_2.setFont(font)
        self.error_lbl_2.setStyleSheet("color: rgb(239, 0, 0);\n"
"background-color: rgba(255, 255, 255, 00);")
        self.error_lbl_2.setText("")
        self.error_lbl_2.setObjectName("error_lbl_2")
        self.stackedWidget.addWidget(self.join_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.label_4 = QtWidgets.QLabel(self.main_page)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 550, 35))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.time_lbl = QtWidgets.QLabel(self.main_page)
        self.time_lbl.setGeometry(QtCore.QRect(7, 6, 45, 25))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.time_lbl.setFont(font)
        self.time_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.time_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.time_lbl.setObjectName("time_lbl")
        self.label_6 = QtWidgets.QLabel(self.main_page)
        self.label_6.setGeometry(QtCore.QRect(373, 11, 16, 15))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("img/mute.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.main_page)
        self.label_7.setGeometry(QtCore.QRect(387, 4, 36, 30))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("img/wifi.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.main_page)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 22, 18))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("img/kakako.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.main_page)
        self.label_8.setGeometry(QtCore.QRect(511, 6, 38, 25))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("img/b.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.main_page)
        self.label_9.setGeometry(QtCore.QRect(423, 6, 18, 12))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.main_page)
        self.label_10.setGeometry(QtCore.QRect(423, 19, 30, 12))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.main_page)
        self.label_11.setGeometry(QtCore.QRect(485, 11, 27, 16))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.main_page)
        self.label_12.setGeometry(QtCore.QRect(456, 9, 25, 20))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("img/s.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(self.main_page)
        self.label_2.setGeometry(QtCore.QRect(0, 35, 550, 55))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(131, 160, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(216, 216, 216);\n"
"border-style:dashed;\n"
"border-width:2px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.search_line = QtWidgets.QLineEdit(self.main_page)
        self.search_line.setGeometry(QtCore.QRect(270, 46, 231, 31))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.search_line.setFont(font)
        self.search_line.setStyleSheet("border-color: rgb(131, 160, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"")
        self.search_line.setText("")
        self.search_line.setObjectName("search_line")
        self.search_lbl = QtWidgets.QLabel(self.main_page)
        self.search_lbl.setGeometry(QtCore.QRect(505, 46, 33, 30))
        self.search_lbl.setText("")
        self.search_lbl.setPixmap(QtGui.QPixmap("img/71403.png"))
        self.search_lbl.setScaledContents(True)
        self.search_lbl.setObjectName("search_lbl")
        self.scrollArea = QtWidgets.QScrollArea(self.main_page)
        self.scrollArea.setGeometry(QtCore.QRect(10, 185, 530, 550))
        self.scrollArea.setStyleSheet("border-color: rgb(223, 223, 223);\n"
"background-color: rgb(240, 243, 255);\n"
"border-style:solid;\n"
"border-width:1px;\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 528, 548))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 527, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_13 = QtWidgets.QLabel(self.main_page)
        self.label_13.setGeometry(QtCore.QRect(0, 90, 550, 53))
        self.label_13.setStyleSheet("")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.location_btn = QtWidgets.QPushButton(self.main_page)
        self.location_btn.setGeometry(QtCore.QRect(83, 95, 90, 42))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.location_btn.setFont(font)
        self.location_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:3px;\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(131, 160, 255);\n"
"border-style:solid;\n"
"color:rgb(131, 160, 255);")
        self.location_btn.setObjectName("location_btn")
        self.restaurant_btn = QtWidgets.QPushButton(self.main_page)
        self.restaurant_btn.setGeometry(QtCore.QRect(232, 95, 90, 42))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.restaurant_btn.setFont(font)
        self.restaurant_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:3px;\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(131, 160, 255);\n"
"border-style:solid;\n"
"color:rgb(131, 160, 255);")
        self.restaurant_btn.setObjectName("restaurant_btn")
        self.hotel_btn = QtWidgets.QPushButton(self.main_page)
        self.hotel_btn.setGeometry(QtCore.QRect(375, 95, 90, 42))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hotel_btn.setFont(font)
        self.hotel_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-width:3px;\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(131, 160, 255);\n"
"border-style:solid;\n"
"color:rgb(131, 160, 255);")
        self.hotel_btn.setObjectName("hotel_btn")
        self.esc_btn2 = QtWidgets.QPushButton(self.main_page)
        self.esc_btn2.setGeometry(QtCore.QRect(255, 747, 41, 35))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.esc_btn2.setFont(font)
        self.esc_btn2.setStyleSheet("border-style:solid;\n"
"border-width:4px;\n"
"border-radius:10px;\n"
"border-color: rgb(131, 160, 255);\n"
"")
        self.esc_btn2.setText("")
        self.esc_btn2.setObjectName("esc_btn2")
        self.label_14 = QtWidgets.QLabel(self.main_page)
        self.label_14.setGeometry(QtCore.QRect(420, 747, 56, 40))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(131, 160, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.main_page)
        self.label_15.setGeometry(QtCore.QRect(60, 738, 78, 55))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("img/menu.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.main_page)
        self.label_16.setGeometry(QtCore.QRect(0, 81, 10, 16))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.main_page)
        self.label_17.setGeometry(QtCore.QRect(540, 82, 10, 16))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.comboBox = QtWidgets.QComboBox(self.main_page)
        self.comboBox.setGeometry(QtCore.QRect(429, 150, 111, 26))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border-style:solid;\n"
"color: rgb(131, 160, 255);\n"
"border-width:2px;\n"
"border-color: rgb(131, 160, 255);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget.addWidget(self.main_page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.id_lbl.setText(_translate("Form", "아이디"))
        self.pw_lbl.setText(_translate("Form", "패스워드"))
        self.login_btn.setText(_translate("Form", "로그인"))
        self.join_btn.setText(_translate("Form", "회원가입"))
        self.esc_btn.setText(_translate("Form", "종료"))
        self.main_lbl.setText(_translate("Form", "붓싼"))
        self.label.setText(_translate("Form", "회원 가입"))
        self.name_lbl.setText(_translate("Form", "이름"))
        self.id_lbl2.setText(_translate("Form", "아이디"))
        self.pw_lbl2.setText(_translate("Form", "패스워드"))
        self.pwch_lbl.setText(_translate("Form", "패스워드 확인"))
        self.age_com.setItemText(0, _translate("Form", "10대"))
        self.age_com.setItemText(1, _translate("Form", "20대"))
        self.age_com.setItemText(2, _translate("Form", "30대"))
        self.age_com.setItemText(3, _translate("Form", "40대"))
        self.age_com.setItemText(4, _translate("Form", "50대"))
        self.age_com.setItemText(5, _translate("Form", "60대"))
        self.age_com.setItemText(6, _translate("Form", "70대"))
        self.age_lbl.setText(_translate("Form", "나이"))
        self.cancel_btn.setText(_translate("Form", "취소"))
        self.clear_btn.setText(_translate("Form", "완료"))
        self.time_lbl.setText(_translate("Form", "7:33"))
        self.label_9.setText(_translate("Form", "HD"))
        self.label_10.setText(_translate("Form", "voice"))
        self.label_11.setText(_translate("Form", "92%"))
        self.label_2.setText(_translate("Form", " 붓싼"))
        self.location_btn.setText(_translate("Form", "관광지"))
        self.restaurant_btn.setText(_translate("Form", "맛집"))
        self.hotel_btn.setText(_translate("Form", "숙소"))
        self.esc_btn2.setToolTip(_translate("Form", "종료"))
        self.label_14.setText(_translate("Form", "<"))
        self.label_15.setToolTip(_translate("Form", "일정표"))
        self.comboBox.setItemText(0, _translate("Form", "전체"))
        self.comboBox.setItemText(1, _translate("Form", "중구"))
        self.comboBox.setItemText(2, _translate("Form", "서구"))
        self.comboBox.setItemText(3, _translate("Form", "동구"))
        self.comboBox.setItemText(4, _translate("Form", "영도구"))
        self.comboBox.setItemText(5, _translate("Form", "부산진구"))
        self.comboBox.setItemText(6, _translate("Form", "동래구"))
        self.comboBox.setItemText(7, _translate("Form", "남구"))
        self.comboBox.setItemText(8, _translate("Form", "북구"))
        self.comboBox.setItemText(9, _translate("Form", "해운대구"))
        self.comboBox.setItemText(10, _translate("Form", "사하구"))
        self.comboBox.setItemText(11, _translate("Form", "금정구"))
        self.comboBox.setItemText(12, _translate("Form", "강서구"))
        self.comboBox.setItemText(13, _translate("Form", "연제구"))
        self.comboBox.setItemText(14, _translate("Form", "수영구"))
        self.comboBox.setItemText(15, _translate("Form", "사상구"))
        self.comboBox.setItemText(16, _translate("Form", "기장군"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
