# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(510, 100)
        Form.setMinimumSize(QtCore.QSize(510, 100))
        Form.setMaximumSize(QtCore.QSize(510, 100))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 510, 100))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 140, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/background.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 17, 345, 24))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(151, 47, 345, 16))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(151, 70, 161, 16))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "관광지 or 맛집 or 숙소 이름 들어가는 라벨"))
        self.label_3.setText(_translate("Form", "부산광역시 영도구 흰여울길"))
        self.label_4.setText(_translate("Form", "영도구"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
